### ISSUE TITLE
push to production

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/webob.org#1]
@blaflamme I assume you're the person who can update this website? I pushed a couple of commits to the repo.

**Comment by blaflamme** [comment]
@stevepiercy there's no repo setup, so I just replaced the index file for the moment.

**Comment by stevepiercy** [comment]
@blaflamme good enough for now.

There's another greater question, is a marketing website needed for WebOb, now that we have http://pylonsproject.org/projects.html ?

@bertjwregeer may have an opinion, too.

**Comment by digitalresistor** [comment]
WebOb as it stands is used by a much larger contingency than just the Pylons Project itself, for example it underpins almost all of the OpenStack projects.

I don't think rolling it all up into a page that just lists the projects that the Pylons Project maintains is the correct course of action. It's more akin to Pyramid and Pylons in that it is one of the bigger projects we maintain and work on.

Since we have the webob.org domain, and due to the fact that it is heavily used outside of the Pylons Project I'd like to do a website that contains a little more about WebOb, how to use it, what it provides, and link to the various projects that have built on top of it.

**Comment by stevepiercy** [comment]
@bertjwregeer OK, thanks for enlightening me.

I will close this issue, as the changes have been pushed to production.

Let's discuss how to present WebOb in #pyramid on IRC, then create issues as needed.
